services:
  card-validator:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: card-validator
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      HOST: ${HOST}
      BIN_API_URL: ${BIN_API_URL}
      BIN_API_KEY: ${BIN_API_KEY}
    ports:
      - '${PORT}:${PORT}'